using System.Collections.Generic;
using System.IO;
using EchoesOfTheVoid.Core.Combat;
using EchoesOfTheVoid.Core.Combat.ScriptableObjects;
using EchoesOfTheVoid.Core.Inventory;
using EchoesOfTheVoid.Core.Inventory.Data;
using EchoesOfTheVoid.Core.Inventory.ScriptableObjects;
using UnityEditor;
using UnityEngine;

namespace EchoesOfTheVoid.Editor {
  public static class ScriptableObjectRegenerator {
    private const string SkillsFolder = "Assets/ScriptableObjects/Combat/Skills";
    private const string EquipmentFolder = "Assets/ScriptableObjects/Inventory/Equipment";
    private const string AssetLabel = "AutoGeneratedTestAsset";

    [MenuItem("Tools/Echoes/Regenerate Test Scriptable Objects", priority = 200)]
    public static void Regenerate() {
      AssetDatabase.StartAssetEditing();
      try {
        CreateSkillAssets();
        CreateEquipmentAssets();
      } finally {
        AssetDatabase.StopAssetEditing();
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
      }

      Debug.Log("Regenerated test ScriptableObject assets for skills and equipment.");
    }

    private static void CreateSkillAssets() {
      EnsureDirectory(SkillsFolder);

      CreateOrUpdateSkill(
        id: "skill_test_ember_bolt",
        displayName: "Ember Bolt",
        description: "Unleashes a focused bolt of fire at a single foe.",
        manaCost: 8,
        staminaCost: 0,
        cooldown: 1,
        targetType: TargetType.Single,
        canTargetSelf: false,
        canTargetAllies: false,
        canTargetEnemies: true,
        effect: new SkillEffectData {
          EffectType = EffectType.Damage,
          BaseValue = 42,
          StatScaling = 0.6f,
          ScalingStat = StatType.Attack,
          TargetSelf = false
        },
        animationTrigger: "CastFire"
      );

      CreateOrUpdateSkill(
        id: "skill_test_starlight_mending",
        displayName: "Starlight Mending",
        description: "Bathes an ally in restorative starlight.",
        manaCost: 10,
        staminaCost: 0,
        cooldown: 2,
        targetType: TargetType.Single,
        canTargetSelf: true,
        canTargetAllies: true,
        canTargetEnemies: false,
        effect: new SkillEffectData {
          EffectType = EffectType.Heal,
          BaseValue = 35,
          StatScaling = 0.5f,
          ScalingStat = StatType.Mana,
          TargetSelf = false
        },
        animationTrigger: "CastHeal"
      );
    }

    private static void CreateOrUpdateSkill(
      string id,
      string displayName,
      string description,
      int manaCost,
      int staminaCost,
      int cooldown,
      TargetType targetType,
      bool canTargetSelf,
      bool canTargetAllies,
      bool canTargetEnemies,
      SkillEffectData effect,
      string animationTrigger
    ) {
      string assetPath = BuildAssetPath(SkillsFolder, id);
      SkillScriptableObject asset = LoadOrCreate<SkillScriptableObject>(assetPath);

      asset.SkillId = id;
      asset.DisplayName = displayName;
      asset.Description = description;
      asset.ManaCost = manaCost;
      asset.StaminaCost = staminaCost;
      asset.CooldownTurns = cooldown;
      asset.TargetType = targetType;
      asset.CanTargetSelf = canTargetSelf;
      asset.CanTargetAllies = canTargetAllies;
      asset.CanTargetEnemies = canTargetEnemies;
      asset.Effects = new List<SkillEffectData> { effect };
      asset.AnimationTrigger = animationTrigger;

      EditorUtility.SetDirty(asset);
      ApplyDefaultLabel(asset);
    }

    private static void CreateEquipmentAssets() {
      var definitions = new[] {
        new EquipmentDefinition("item_test_head_starbound_tiara", "Starbound Tiara", EquipmentSlotType.Head, "Gleaming circlet that sharpens arcane focus.", StatType.Mana, 12, 0.1f),
        new EquipmentDefinition("item_test_head_ashen_vanguard_visor", "Ashen Vanguard Visor", EquipmentSlotType.Head, "Reinforced visor that fortifies resolve.", StatType.Defense, 8, 0.05f),

        new EquipmentDefinition("item_test_chest_solaris_plate", "Solaris Plate", EquipmentSlotType.Chest, "Radiant plate harnessed from ancient sunforges.", StatType.Defense, 18, 0.08f),
        new EquipmentDefinition("item_test_chest_voidsilk_robes", "Voidsilk Robes", EquipmentSlotType.Chest, "Silken robes that hum with void energy.", StatType.Mana, 20, 0.12f),

        new EquipmentDefinition("item_test_legs_tempest_greaves", "Tempest Greaves", EquipmentSlotType.Legs, "Greaves that channel storm winds into swift steps.", StatType.Speed, 6, 0.07f),
        new EquipmentDefinition("item_test_legs_earthshaper_treads", "Earthshaper Treads", EquipmentSlotType.Legs, "Weighted treads that steady every stride.", StatType.Defense, 10, 0.06f),

        new EquipmentDefinition("item_test_mainhand_celestial_blade", "Celestial Blade", EquipmentSlotType.MainHand, "One-handed blade balanced for precise strikes.", StatType.Attack, 22, 0.12f, occupiesBothHands: false),
        new EquipmentDefinition("item_test_mainhand_twinspike_halberd", "Twinspike Halberd", EquipmentSlotType.MainHand, "Polearm that demands both hands for control.", StatType.Attack, 34, 0.18f, occupiesBothHands: true),

        new EquipmentDefinition("item_test_offhand_guardian_bulwark", "Guardian Bulwark", EquipmentSlotType.OffHand, "Tower shield etched with protective glyphs.", StatType.Defense, 24, 0.14f),
        new EquipmentDefinition("item_test_offhand_runic_focus", "Runic Focus", EquipmentSlotType.OffHand, "Focus crystal that amplifies spellcraft.", StatType.Mana, 15, 0.15f),

        new EquipmentDefinition("item_test_accessory_aurora_band", "Aurora Band", EquipmentSlotType.Accessory, "Band that resonates with aurora currents.", StatType.Luck, 5, 0.09f),
        new EquipmentDefinition("item_test_accessory_echoing_signet", "Echoing Signet", EquipmentSlotType.Accessory, "Signet that stores fragments of echoes.", StatType.Attack, 8, 0.07f),

        new EquipmentDefinition("item_test_relic_emberheart_core", "Emberheart Core", EquipmentSlotType.Relic, "Sealed ember that pulses with primal fire.", StatType.Attack, 12, 0.1f),
        new EquipmentDefinition("item_test_relic_starseer_compass", "Starseer Compass", EquipmentSlotType.Relic, "Compass that aligns with constellations for guidance.", StatType.Luck, 10, 0.11f),
      };

      foreach (EquipmentDefinition definition in definitions) {
        string slotFolder = Path.Combine(EquipmentFolder, definition.Slot.ToString());
        EnsureDirectory(slotFolder);

        string assetPath = BuildAssetPath(slotFolder, definition.ItemId);
        EquipmentItemScriptableObject asset = LoadOrCreate<EquipmentItemScriptableObject>(assetPath);

        asset.ItemId = definition.ItemId;
        asset.DisplayName = definition.DisplayName;
        asset.Description = definition.Description;
        asset.ConsumableInCombat = false;
        asset.UsableOutsideCombat = false;
        asset.Slot = definition.Slot;
        asset.OccupiesBothHands = definition.OccupiesBothHands;
        asset.StatModifiers = new List<EquipmentStatModifier> {
          new EquipmentStatModifier {
            Stat = definition.PrimaryStat,
            FlatBonus = definition.FlatBonus,
            PercentBonus = definition.PercentBonus
          }
        };

        EditorUtility.SetDirty(asset);
        ApplyDefaultLabel(asset);
      }
    }

    private static T LoadOrCreate<T>(string assetPath) where T : ScriptableObject {
      T asset = AssetDatabase.LoadAssetAtPath<T>(assetPath);
      if (asset != null) {
        return asset;
      }

      asset = ScriptableObject.CreateInstance<T>();
      AssetDatabase.CreateAsset(asset, assetPath);
      return asset;
    }

    private static string BuildAssetPath(string folder, string id) {
      string fileName = $"{id}.asset";
      return Path.Combine(folder, fileName).Replace('\\', '/');
    }

    private static void EnsureDirectory(string folderPath) {
      string fullPath = Path.GetFullPath(folderPath);
      if (!Directory.Exists(fullPath)) {
        Directory.CreateDirectory(fullPath);
      }
    }

    private static void ApplyDefaultLabel(UnityEngine.Object asset) {
      string[] existing = AssetDatabase.GetLabels(asset);
      if (System.Array.IndexOf(existing, AssetLabel) >= 0) {
        return;
      }

      List<string> labels = new List<string>(existing) { AssetLabel };
      AssetDatabase.SetLabels(asset, labels.ToArray());
    }

    private readonly struct EquipmentDefinition {
      public EquipmentDefinition(
        string itemId,
        string displayName,
        EquipmentSlotType slot,
        string description,
        StatType primaryStat,
        int flatBonus,
        float percentBonus,
        bool occupiesBothHands = false
      ) {
        ItemId = itemId;
        DisplayName = displayName;
        Slot = slot;
        Description = description;
        PrimaryStat = primaryStat;
        FlatBonus = flatBonus;
        PercentBonus = percentBonus;
        OccupiesBothHands = occupiesBothHands;
      }

      public string ItemId { get; }
      public string DisplayName { get; }
      public EquipmentSlotType Slot { get; }
      public string Description { get; }
      public StatType PrimaryStat { get; }
      public int FlatBonus { get; }
      public float PercentBonus { get; }
      public bool OccupiesBothHands { get; }
    }
  }
}
